# Generated by Django 5.0.14 on 2026-08-17 18:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower numbers appear first in the BU tab strip. Ties break alphabetically.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "business unit",
                "verbose_name_plural": "business units",
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "position",
                    models.CharField(
                        db_index=True,
                        help_text="Job title exactly as it appears in the grading structure.",
                        max_length=255,
                    ),
                ),
                (
                    "band",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Band label, e.g. 'Band 6.2'.",
                        max_length=40,
                    ),
                ),
                (
                    "band_numeric",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        help_text="Auto-derived from the band label; used for sorting and career-path maths.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("99")),
                        ],
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Leadership level, e.g. 'Change Leader'.",
                        max_length=80,
                    ),
                ),
                (
                    "experience",
                    models.TextField(blank=True, help_text="Experience required."),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True,
                        help_text="Academic and professional qualifications.",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True, help_text="Role purpose / description."
                    ),
                ),
                (
                    "focus_areas",
                    models.TextField(
                        blank=True,
                        help_text="Key focus areas. Comma-separated in the legacy data.",
                    ),
                ),
                (
                    "kras",
                    models.TextField(
                        blank=True, help_text="Key performance measures / KRAs."
                    ),
                ),
                (
                    "direct_reports",
                    models.TextField(
                        blank=True, help_text="Direct reports, or 'None'."
                    ),
                ),
                (
                    "technical_competencies",
                    models.TextField(
                        blank=True,
                        help_text="Technical / functional competencies. Pipe-separated in the legacy data.",
                    ),
                ),
                (
                    "leadership_competencies",
                    models.TextField(
                        blank=True,
                        help_text="Leadership competencies. Pipe-separated in the legacy data.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unticked roles are hidden from the public site but kept for history.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="manual",
                        editable=False,
                        help_text="'seed' if it came from the legacy HTML, 'manual' if a person created it.",
                        max_length=20,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=64
                    ),
                ),
                (
                    "business_unit",
                    models.ForeignKey(
                        help_text="BU or Group function this role sits in.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="roles.businessunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": (
                    "business_unit__display_order",
                    "business_unit__name",
                    "band_numeric",
                    "position",
                ),
            },
        ),
        migrations.CreateModel(
            name="RoleRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_label",
                    models.CharField(
                        help_text="Denormalised '<BU> / <position>' so the trail survives deletion.",
                        max_length=320,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("seed", "Seeded from HTML"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=150)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{field: {'from': old, 'to': new}} for updates; full snapshot for create/delete.",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="roles.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "role revision",
                "verbose_name_plural": "role revisions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("question", models.TextField()),
                ("succeeded", models.BooleanField(db_index=True, default=False)),
                ("error_code", models.CharField(blank=True, max_length=40)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("request_id", models.CharField(blank=True, max_length=36)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI request log",
                "verbose_name_plural": "AI request logs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["-created_at", "succeeded"], name="ai_created_ok_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="businessunit",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="roles_busin_is_acti_38f071_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active", "business_unit"], name="role_active_bu_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["band_numeric", "position"], name="role_band_pos_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["level"], name="role_level_idx"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("business_unit", "position"),
                name="uniq_role_per_bu",
                violation_error_message="A role with this title already exists in this business unit.",
            ),
        ),
        migrations.AddIndex(
            model_name="rolerevision",
            index=models.Index(
                fields=["-created_at", "action"], name="rev_created_action_idx"
            ),
        ),
    ]
