# Generated by Django 5.0.14 on 2026-08-20 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("succeeded", models.BooleanField(db_index=True, default=False)),
                ("user_agent", models.CharField(blank=True, max_length=200)),
                ("request_id", models.CharField(blank=True, max_length=36)),
            ],
            options={
                "verbose_name": "login attempt",
                "verbose_name_plural": "login attempts",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["ip", "-created_at"], name="login_ip_time_idx"
                    ),
                    models.Index(
                        fields=["username", "-created_at"], name="login_user_time_idx"
                    ),
                ],
            },
        ),
    ]
